server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lab.vallegrande.edu.pe/keycloak-security/realms/prs-realm

  r2dbc:
    url: r2dbc:postgresql://ep-sweet-cherry-ac1jujjy-pooler.sa-east-1.aws.neon.tech/paymentsservice?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_JPQSp1e0TCj0
    
  sql:
    init:
      mode: never
      
  codec:
    max-in-memory-size: 20MB

logging:
  level:
    # Se agregaron corchetes y comillas para evitar la advertencia de caracteres especiales
    "[org.springframework.r2dbc]": DEBUG
    "[org.springframework.transaction]": DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

external:
  services:
    books:
      url: https://lab.vallegrande.edu.pe/fideiNexus-books/v1/books
    requests:
      url: https://lab.vallegrande.edu.pe/fideiNexus-solicitud/v1/requests
    people:
      url: https://lab.vallegrande.edu.pe/fideiNexus-persona/v1/people