server:
  port: 8086

spring:
  r2dbc:
    url: r2dbc:postgresql://ep-dark-water-aq88s0ca-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_qPKa5eZid8Jf
  sql:
    init:
      mode: always
  codec:
    max-in-memory-size: 20MB

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

external:
  services:
    books:
      url: http://localhost:8088/v1/books
