-- ================================================
-- Microservicio de Finanzas - FideiNexus
-- Schema SQL: se ejecuta automáticamente al iniciar
-- ================================================

CREATE TABLE IF NOT EXISTS documento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_ocr     VARCHAR(255),
    fecha_registro TIMESTAMP,
    nombre_archivo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255),
    nombre      VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS reasons (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT,
    nombre      VARCHAR(100) NOT NULL,
    request_id  INTEGER
);

CREATE TABLE IF NOT EXISTS finanzas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP,
    estado            VARCHAR(1),
    fecha_pago        DATE NOT NULL,
    monto             NUMERIC(10, 2) NOT NULL,
    people_id         INTEGER NOT NULL,
    referencia        VARCHAR(150),
    tenant_id         INTEGER NOT NULL,
    payment_method_id BIGINT NOT NULL REFERENCES payment_methods(id),
    reason_id         BIGINT NOT NULL REFERENCES reasons(id),
    book_id           INTEGER
);

-- Datos semilla (opcional, ajustados a los nuevos nombres)
INSERT INTO payment_methods (id, nombre, descripcion)
VALUES
    (1, 'Yape',                 'Pago mediante app Yape'),
    (2, 'Plin',                 'Pago mediante app Plin'),
    (3, 'Efectivo',             'Pago en efectivo'),
    (4, 'Transferencia Bancaria','Transferencia bancaria directa')
ON CONFLICT (id) DO NOTHING;

INSERT INTO reasons (id, nombre, descripcion, request_id)
VALUES
    (1, 'Fianza por Matrimonio',    'Fianza requerida para tramitar matrimonio', NULL),
    (2, 'Trámite de Certificado',   'Pago por emisión de acta o certificado sacramental', NULL),
    (3, 'Reserva de Misa',          'Pago por reserva de misa parroquial', NULL)
ON CONFLICT (id) DO NOTHING;
